version: '3'
services:
  ### Postgres database for Car Inventory
  db-car-inventory:
    container_name: db-car-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_inventory
      POSTGRES_USER: rentalCars
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  ### Postgres database for Booking
  db-booking:
    container_name: db-booking
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: rentalCars
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434

  ### Postgres database for Payments
  db-payments:
    container_name: db-payments
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: rentalCars
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433
## TODO:
### VERIFICAR LOS CONTENEDORES EN DOCKER DESKTOP, PUEDE QUE HAYA UNO REPETIDO QUE SE LLAME PARECIDO